'use strict';
(() => {
  const $ = id => document.getElementById(id), canvas = $('canvas'), ctx = canvas.getContext('2d');
  const mobile = matchMedia('(pointer:coarse)').matches || navigator.maxTouchPoints > 0;
  const reduced = matchMedia('(prefers-reduced-motion:reduce)').matches;
  const W = 420, H = 720, home = {x:210,y:574,r:28};
  const images = ['9205904d.jpg','b2915aab.jpg','cb754493.jpg','dab3b287.jpg','db9c07a2.jpg','07eaf8fb.jpg','cd7724c7.jpg'].map(src => {const image = new Image(); image.src=src; return image;});
  const names = ['境界','迷い路','夜明け前'];
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), rand=(a,b)=>a+Math.random()*(b-a);
  const pointers = new Map(), keys = new Set(); let primary=null, state='title', previous=0, g, best=0;
  try {best=Number(localStorage.getItem('kiro-best'))||0;} catch {}
  $('best').textContent=`BEST ${String(best).padStart(6,'0')}`;
  $('moveHelp').textContent=mobile?'画面のどこでも、指を滑らせた分だけ移動。指を置いた場所へは飛びません。':'マウスで移動。矢印キー / WASD でも操作できます。';
  $('castHelp').textContent=mobile?'1本目を触れたまま、2本目の指を画面のどこかにタップすると祓い。':'ゲーム画面をクリックすると祓い。右下の「祓」ボタンでも発動。';
  $('gesture').textContent=mobile?'2本目の指をタップで祓い':'クリックで祓い';
  function resetInput(){pointers.clear();primary=null;keys.clear();}
  function resize(){const r=canvas.getBoundingClientRect(), d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}
  new ResizeObserver(resize).observe(canvas);
  function newGame(){g={p:{x:home.x,y:home.y},life:3,wards:0,total:0,score:0,night:0,t:0,elapsed:0,spawn:2,drop:3,inv:2,bullets:[],enemies:[],items:[],shots:[],rings:[],boss:null,fire:0,notice:0,damage:0};state='play';resetInput();$('overlay').hidden=true;$('pause').textContent='Ⅱ';say('第一夜　境界',2.5);sync();}
  function say(text,time=2){$('notice').textContent=text;g.notice=time;$('notice').classList.add('show');}
  function sync(){if(!g)return;$('chapter').textContent=`第${['一','二','三'][g.night]}夜 / ${names[g.night]}`;$('hearts').textContent='● '.repeat(g.life)+'○ '.repeat(3-g.life);$('hearts').setAttribute('aria-label',`残機${g.life}`);$('wards').textContent='▰ '.repeat(g.wards)+'▯ '.repeat(3-g.wards);$('spell').textContent=g.wards===3?'大祓い — 全消去 ＋ 結界':g.wards?'祓い — 危険を消し去る':'光る御札を拾おう';$('purify').disabled=!g.wards||state!=='play';$('purify').classList.toggle('ready',g.wards===3);$('bossbar').hidden=!g.boss;$('phase').textContent=g.boss?`自動射撃 / 霊力 ${Math.min(5,1+Math.floor(g.total/3))}`:'道を塞ぐものまで';$('time').textContent=g.boss?'祓魔':`00:${String(Math.max(0,Math.ceil(45-g.t))).padStart(2,'0')}`;if(g.boss)$('hp').style.width=`${100*g.boss.hp/g.boss.max}%`;}
  function cast(){if(state!=='play'||!g.wards)return;const big=g.wards===3;g.wards-=big?3:1;g.bullets=[];g.enemies=[];g.inv=Math.max(g.inv,big?4:1.3);g.rings.push({x:g.p.x,y:g.p.y,r:0,life:1,big});g.score+=big?600:100;if(g.boss){g.boss.hp-=big?45:10;if(g.boss.hp<=0)banish();}say(big?'大祓い — 四秒の結界':'祓い — 道が開けた');sync();}
  function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H};}
  const inputSurface=document;
  inputSurface.addEventListener('pointerdown',e=>{if(state!=='play'||e.target.closest('.overlay'))return;if(e.pointerType==='mouse'){if(e.target===canvas&&e.button===0)cast();return;}if(primary===null&&e.target.closest('button,a')&&!e.target.closest('#purify'))return;e.preventDefault();const q=point(e);pointers.set(e.pointerId,q);$('game').setPointerCapture(e.pointerId);if(primary===null){primary=e.pointerId;if(e.target.closest('#purify'))cast();}else cast();});
  inputSurface.addEventListener('pointermove',e=>{if(state!=='play')return;const q=point(e);if(e.pointerType==='mouse'){if(e.target===canvas){g.p.x=clamp(q.x,14,W-14);g.p.y=clamp(q.y,90,H-92);}return;}const old=pointers.get(e.pointerId);if(!old)return;if(e.pointerId===primary){g.p.x=clamp(g.p.x+(q.x-old.x),14,W-14);g.p.y=clamp(g.p.y+(q.y-old.y),90,H-92);}pointers.set(e.pointerId,q);});
  function release(e){pointers.delete(e.pointerId);if(primary===e.pointerId)primary=pointers.keys().next().value??null;}
  for(const type of ['pointerup','pointercancel','lostpointercapture'])inputSurface.addEventListener(type,release);
  $('purify').addEventListener('click',e=>{if(e.detail===0||e.pointerType==='mouse')cast();});
  addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d',' '].includes(k)){if(state==='play'){e.preventDefault();keys.add(k);if(k===' '&&!e.repeat)cast();}}if(k==='escape'&&!e.repeat)pause();});
  addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
  function pause(){if(!g||!['play','paused'].includes(state))return;if(state==='paused'){state='play';$('overlay').hidden=true;$('pause').textContent='Ⅱ';sync();return;}state='paused';resetInput();$('pause').textContent='▶';showCard('ひと休み','夜道は、ここで待っている。','続ける',pause);}
  $('pause').onclick=pause;addEventListener('blur',()=>{resetInput();if(state==='play')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='play')pause();});
  function showCard(title,text,label,fn){const card=document.createElement('div');card.className='card';const eye=document.createElement('div');eye.className='eyebrow';eye.textContent='DON’T LOOK BACK';const h=document.createElement('h1');h.style.fontSize='36px';h.textContent=title;const p=document.createElement('p');p.className='intro';p.textContent=text;const b=document.createElement('button');b.className='primary';b.textContent=label;b.onclick=fn;card.append(eye,h,p,b);$('overlay').replaceChildren(card);$('overlay').hidden=false;}
  function finish(won){state=won?'won':'dead';resetInput();best=Math.max(best,Math.floor(g.score));try{localStorage.setItem('kiro-best',best);}catch{}$('best').textContent=`BEST ${String(best).padStart(6,'0')}`;showCard(won?'朝が、来た。':'道を、見失った。',`第${g.night+1}夜 · 御札 ${g.total}枚 · SCORE ${Math.floor(g.score)}${won?' — あなたは帰ってきた。':' — 小さな光の中心だけが当たり判定。御札は惜しまず使おう。'}`,'もう一度、夜道へ',newGame);sync();}
  function hit(){if(g.inv>0)return;g.life--;g.inv=3;g.damage=.35;g.bullets=[];g.enemies=[];if(!g.life){finish(false);return;}say('まだ、歩ける。',1.8);sync();}
  function spawnEnemy(){if(g.enemies.length>=(mobile?2:3))return;g.enemies.push({x:rand(55,365),y:-45,r:26,age:0,fire:1.9,vy:rand(31,42),image:images[Math.floor(rand(0,images.length))],seed:rand(0,10)});}
  // Hidden starting-point route: obstacles curve around this point instead of granting immunity.
  function avoidHome(o,nx,ny,pad){const dx=nx-o.x,dy=ny-o.y,len=dx*dx+dy*dy,t=len?clamp(((home.x-o.x)*dx+(home.y-o.y)*dy)/len,0,1):0;const r=home.r+pad;if(Math.hypot(o.x+dx*t-home.x,o.y+dy*t-home.y)>=r)return{x:nx,y:ny};const side=o.x<home.x?-1:1,offset=Math.sqrt(Math.max(0,r*r-(ny-home.y)**2));return{x:home.x+side*(offset+2),y:ny};}
  function bullet(x,y,angle,homing=false){if(g.bullets.length>=(mobile?10:16))return;const speed=homing?80:103+g.night*9;g.bullets.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,speed,homing,age:0,r:6});}
  function fireFrom(e,boss=false){const a=Math.atan2(g.p.y-e.y,g.p.x-e.x);if(boss){const n=mobile?3:5;for(let i=0;i<n;i++)bullet(e.x,e.y+20,a+(i-(n-1)/2)*.38,i===0&&g.night>0);}else bullet(e.x,e.y+15,a,Math.random()<.4);}
  function startBoss(){g.enemies=[];g.bullets=[];g.inv=Math.max(g.inv,2);const hp=100+g.night*35;g.boss={x:210,y:155,r:52,hp,max:hp,age:0,fire:2.4,image:images[[0,2,5][g.night]]};say('道を塞ぐもの — 自動射撃に変化',3);sync();}
  function banish(){g.boss=null;g.bullets=[];g.shots=[];g.score+=2000;g.life=Math.min(3,g.life+1);g.inv=3;g.rings.push({x:210,y:150,r:0,life:1,big:true});if(g.night===2){finish(true);return;}g.night++;g.t=0;g.spawn=3;g.drop=2;say(`第${['一','二','三'][g.night]}夜　${names[g.night]} — 命が回復`,3);sync();}
  function update(dt){g.elapsed+=dt;g.inv=Math.max(0,g.inv-dt);g.damage=Math.max(0,g.damage-dt);g.notice-=dt;if(g.notice<=0)$('notice').classList.remove('show');let dx=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),dy=Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'));const norm=Math.hypot(dx,dy)||1;g.p.x=clamp(g.p.x+dx/norm*235*dt,14,W-14);g.p.y=clamp(g.p.y+dy/norm*235*dt,90,H-92);
    if(!g.boss){g.t+=dt;g.spawn-=dt;if(g.spawn<=0){spawnEnemy();g.spawn=(mobile?4.6:3.7)-g.night*.35;}if(g.t>=45)startBoss();}else{const b=g.boss;b.age+=dt;b.x=210+Math.sin(b.age*.65)*112;b.y=155+Math.sin(b.age*.9)*16;b.fire-=dt;if(b.fire<=0){fireFrom(b,true);b.fire=(mobile?2.5:2.1)-g.night*.15;}g.fire-=dt;if(g.fire<=0){const a=Math.atan2(b.y-g.p.y,b.x-g.p.x);g.shots.push({x:g.p.x,y:g.p.y,vx:Math.cos(a)*460,vy:Math.sin(a)*460,age:0,damage:2+Math.min(4,g.total*.35)});g.fire=.24;}if(Math.hypot(g.p.x-b.x,g.p.y-b.y)<b.r-10)hit();}
    if(state!=='play')return;g.drop-=dt;if(g.drop<=0){if(g.items.length<2)g.items.push({x:rand(65,355),y:rand(290,455),age:0});g.drop=7;}
    for(const e of g.enemies){e.age+=dt;const next=avoidHome(e,e.x+Math.sin(e.age+e.seed)*9*dt,e.y+e.vy*dt,e.r);e.x=next.x;e.y=next.y;e.fire-=dt;if(e.fire<=0&&e.y<480){fireFrom(e);e.fire=3.4;}if(Math.hypot(e.x-g.p.x,e.y-g.p.y)<e.r-6)hit();}
    const resting=Math.hypot(g.p.x-home.x,g.p.y-home.y)<2;
    for(const o of g.bullets){o.age+=dt;if(o.homing&&o.age<2.4){const target=resting?{x:home.x+(o.x<home.x?-90:90),y:home.y}:g.p;let angle=Math.atan2(o.vy,o.vx),delta=Math.atan2(target.y-o.y,target.x-o.x)-angle;delta=Math.atan2(Math.sin(delta),Math.cos(delta));angle+=clamp(delta,-.65*dt,.65*dt);o.vx=Math.cos(angle)*o.speed;o.vy=Math.sin(angle)*o.speed;}const next=avoidHome(o,o.x+o.vx*dt,o.y+o.vy*dt,o.r);o.x=next.x;o.y=next.y;if(Math.hypot(g.p.x-o.x,g.p.y-o.y)<o.r+4)hit();}
    if(state!=='play')return;for(const s of g.shots){s.age+=dt;s.x+=s.vx*dt;s.y+=s.vy*dt;if(g.boss&&Math.hypot(s.x-g.boss.x,s.y-g.boss.y)<g.boss.r){g.boss.hp-=s.damage;s.age=10;if(g.boss.hp<=0){banish();break;}}}
    for(const item of g.items){item.age+=dt;if(Math.hypot(item.x-g.p.x,item.y-g.p.y)<29){item.age=99;g.total++;g.wards=Math.min(3,g.wards+1);g.score+=150;say(g.wards===3?'御札三枚 — 大祓いが使える':'御札を拾った — 霊力が上昇',1.5);}}
    g.enemies=g.enemies.filter(e=>e.y<H+50);g.bullets=g.bullets.filter(o=>o.age<7&&o.x>-30&&o.x<W+30&&o.y>-30&&o.y<H+30);g.items=g.items.filter(i=>i.age<13);g.shots=g.shots.filter(s=>s.age<2);g.rings=g.rings.filter(r=>{r.life-=dt;r.r+=700*dt;return r.life>0;});g.score+=dt*10;sync();
  }
  function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
  function face(e,boss=false){ctx.save();const r=e.r;ctx.globalAlpha=Math.min(1,e.age*1.8);ctx.shadowColor=boss?'#944342':'#1f2d23';ctx.shadowBlur=18;ctx.beginPath();ctx.ellipse(e.x,e.y,r,r*1.18,0,0,Math.PI*2);ctx.clip();if(e.image.complete&&e.image.naturalWidth){const im=e.image,side=Math.min(im.naturalWidth,im.naturalHeight);ctx.drawImage(im,(im.naturalWidth-side)/2,(im.naturalHeight-side)/2,side,side,e.x-r,e.y-r*1.18,r*2,r*2.36);}else{ellipse(e.x,e.y,r,r,'#48453f');ellipse(e.x-8,e.y,4,7,'#050505');ellipse(e.x+8,e.y,4,7,'#050505');}ctx.fillStyle='#111b1325';ctx.fillRect(e.x-r,e.y-r*1.2,r*2,r*2.4);ctx.restore();if(e.fire<.65){ctx.strokeStyle='#be776c';ctx.lineWidth=1;ctx.beginPath();ctx.arc(e.x,e.y,r+7,0,Math.PI*2*(1-e.fire/.65));ctx.stroke();}}
  function render(now){ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0);const t=g?.elapsed||now/1000;ctx.fillStyle='#0b110f';ctx.fillRect(0,0,W,H);const fog=ctx.createRadialGradient(210,310,5,210,360,430);fog.addColorStop(0,'#30382b');fog.addColorStop(1,'#050a09');ctx.fillStyle=fog;ctx.fillRect(0,0,W,H);ctx.fillStyle='#192119';ctx.beginPath();ctx.moveTo(165,0);ctx.lineTo(255,0);ctx.lineTo(390,H);ctx.lineTo(30,H);ctx.fill();ctx.strokeStyle='#707a5422';ctx.lineWidth=1;for(let i=0;i<14;i++){const y=((i*65+t*(reduced?0:38))%850)-65;ctx.beginPath();ctx.moveTo(155-y*.17,y);ctx.lineTo(265+y*.17,y+7);ctx.stroke();}for(let i=0;i<9;i++){const y=((i*107+t*(reduced?0:24))%900)-90;ctx.fillStyle='#060c0b';ctx.fillRect(16+(i%3)*12,y,7,75);ctx.fillRect(380-(i%3)*15,y+35,9,95);}const vignette=ctx.createRadialGradient(210,380,130,210,380,400);vignette.addColorStop(0,'#0000');vignette.addColorStop(1,'#000b');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);
    if(!g)return;for(const item of g.items){ctx.save();ctx.translate(item.x,item.y+(reduced?0:Math.sin(t*2)*4));ctx.rotate(.06);ctx.shadowColor='#e1c57b';ctx.shadowBlur=15;ctx.fillStyle=item.age>11?'#ac9c73':'#e4d3a0';ctx.fillRect(-10,-18,20,36);ctx.shadowBlur=0;ctx.fillStyle='#783e30';ctx.font='17px serif';ctx.textAlign='center';ctx.fillText('祓',0,6);ctx.restore();}for(const e of g.enemies)face(e);if(g.boss)face(g.boss,true);
    for(const o of g.bullets){ctx.save();ctx.translate(o.x,o.y);ctx.rotate(Math.atan2(o.vy,o.vx));ctx.strokeStyle=o.homing?'#9880bd55':'#b7635555';ctx.beginPath();ctx.moveTo(-7,0);ctx.lineTo(-21,0);ctx.stroke();ellipse(0,0,9,5,o.homing?'#ab91d0':'#c97b69');ellipse(1,0,2,4,'#130f15');ctx.restore();}
    ctx.strokeStyle='#eddbab';ctx.lineWidth=2;for(const s of g.shots){ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x-s.vx*.025,s.y-s.vy*.025);ctx.stroke();}for(const r of g.rings){ctx.globalAlpha=r.life;ctx.strokeStyle=r.big?'#f9e5ac':'#bbcbac';ctx.lineWidth=r.big?5:2;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.stroke();}ctx.globalAlpha=1;
    const p=g.p;ctx.save();ctx.translate(p.x,p.y);if(g.inv>0){ctx.strokeStyle='#ddcd9299';ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,0,22,0,Math.PI*2);ctx.stroke();}ctx.shadowColor='#e6e8bb';ctx.shadowBlur=18;ctx.strokeStyle=g.boss?'#e6ca83':'#a4b496';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,-14);ctx.lineTo(9,9);ctx.lineTo(0,5);ctx.lineTo(-9,9);ctx.closePath();ctx.stroke();if(g.boss){ctx.strokeStyle='#e6ca83';ctx.beginPath();ctx.moveTo(-5,-4);ctx.lineTo(-23,12);ctx.lineTo(-16,-12);ctx.moveTo(5,-4);ctx.lineTo(23,12);ctx.lineTo(16,-12);ctx.stroke();for(const side of [-1,1]){ctx.fillStyle='#e4d3a0';ctx.fillRect(side*21-3,-7,6,12);}}ellipse(0,0,4,4,'#fff5ce');ctx.restore();if(g.damage>0&&!reduced){ctx.fillStyle=`rgba(117,39,33,${g.damage*.5})`;ctx.fillRect(0,0,W,H);}
  }
  function frame(now){const dt=Math.min(.033,(now-previous)/1000||0);previous=now;if(state==='play')update(dt);render(now);requestAnimationFrame(frame);}
  $('start').onclick=newGame;resize();requestAnimationFrame(frame);
})();
